spring.application.name=Tienda Online

#Claves reservadas por SpringBoot --> en este caso la modifique para que levante en el puerto 8090
#server.port=8090
server.servlet.context-path=/escuelait/api/v1/endpoints

#Esta claves indica que ebean se inyectara
implementacion.personas=jugadores

#Estos son los parametros dprincipales de toda la aplicacion
app.nombre=Tienda online
app.description=Tienda de Spring Boot para Escuela IT
app.language=es
app.version=1.0

#Connection database
#Datasource configuration
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.initialization-mode=always
#no hace nada.
spring.jpa.hibernate.ddl-auto=none

#toda clases Entity las creará en la BD.
#spring.jpa.hibernate.ddl-auto=create